DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

DROP TABLE ANSERBOARD;

--글 번호 (PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ NOCACHE;

--그룹 번호(새로운 글 등록 시)
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,		--글번호
	GROUPNO NUMBER NOT NULL, 		--그룹번호
	GROUPSQ NUMBER NOT NULL,		--그룹내의 순서
	TITLETAB NUMBER NOT NULL,		--답글의 여백
	TITLE VARCHAR2(2000) NOT NULL,	--제목
	CONTENT VARCHAR2(4000) NOT NULL,--내용
	WRITER VARCHAR2(1000) NOT NULL,	--작성자
	REGDATE DATE NOT NULL			--작성시간
);

SELECT * FROM ANSWERBOARD;


SELECT * FROM ANSWERBOARD 
ORDER BY GROUPNO DESC,GROUPSQ;

--첫번째 글 작성
--TITLETAB 은 답글의 여백을 준다
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'첫번쨰','1번 글입니다','유저1',SYSDATE);




--두 번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'두번쨰 글','2번 글입니다.','유저2',SYSDATE);


--답글 작성(1번글에)
--부모와 같은 그룹 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	'RE:첫번째 글','1번글에 답글입니다.','유저2',SYSDATE);


--세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'세번째 글','3번 글입니다','유저3',SYSDATE);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;


--답글작성(두번째 글에)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		'RE: 두번째 글','2번글의 답글입니다.(1)','유저1',SYSDATE);

--답글작성(RE:두 번째 글 -5)
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1		
		
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		'RE:RE:두번째 글','2번글 답글에 답글(1)','유저2',SYSDATE);
		
--답글작성()
--부모의 GROUPSQ보다 큰 글들의 GROUPSQ+1
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
	AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);
	

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		'RE:두번째 글','2번글에 답글입니다(2)','유저2',SYSDATE);
		
--답글작성(RE:두번째 글 -7)
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
	AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);
	
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
		'RE:RE:두번째 글','2번글에 답글에 답글(2)','유저2',SYSDATE);


SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;

















